import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  const links = [
    { label: "about me", to: "" },
    { label: "work", to: "" },
    { label: "experience", to: "#exp" },
    { label: "blog", to: "" },
    { label: "contact", to: "" },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <span className="font-[satisfy]">PragmaticAweds</span>
        <div className="nav-links">
          {links.map((link, i) => (
            <Link key={"nav-link" + i} href={link.to} className="nav-link">
              <span className="font-[satisfy] mt-[0.2rem] text-sm">
                {"0" + (i + 1) + "."}
              </span>
              <span className="capitalize">{link.label}</span>
            </Link>
          ))}
        </div>
      </nav>
      <main>
        <section className="hero-content">
          <div className="hero-img">
            <Image
              src="/imgs/avatar.webp"
              alt="hero-img"
              width={200}
              height={200}
              quality={100}
            />
          </div>
          <div className="flex flex-col items-center">
            <span className="font-semibold text-xl">Hi, I&apos;m</span>
            <h1 className="text-6xl font-bebas">Abdulafeez Jimoh</h1>
            <h1 className="text-6xl text-[#B9B9B9] font-bebas">
              I use technology to solve human problem
            </h1>
          </div>
        </section>
        <section className="bg-[#C1E5C0] h-[30rem] relative">
          <div className="absolute h-[30rem] w-[50%]">
            <Image
              src="/imgs/art-1.webp"
              alt="section-img"
              fill
              quality={100}
            />
          </div>
        </section>
        <section className="bg-[#C1E5C0] h-[30rem] ">
          <div className=""></div>
        </section>
      </main>
      <footer></footer>
    </>
  );
}
