import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen overflow-hidden flex flex-col">
        <NavBar />
        <main>
          <Header />
          <Projects />
        </main>
        <footer></footer>
      </div>
    </>
  );
}
